'use strict';

module.exports = {
	CREATE_FILE: "CREATE",
	APPEND: "APPEND",
	OPEN: "OPEN",
	MAKE_DIRECTORY: "MKDIRS",
	RENAME: "RENAME",
	DELETE: "DELETE",
	FILE_DETAILS: "GETFILESTATUS",
	DIR_CONTENT: "LISTSTATUS",
	DIR_CONTENT_SUMMARY: "GETCONTENTSUMMARY",
	FILE_CHECKSUM: "GETFILECHECKSUM",
	SET_PERMISSION: "SETPERMISSION"
}
